constraints/annotations/closed.isl, constraints/annotations/closed_any_annotations.isl, constraints/annotations/closed_mixed.isl, constraints/annotations/closed_no_annotations.isl, constraints/annotations/closed_ordered_mixed.isl, constraints/annotations/closed_ordered_optional.isl, constraints/annotations/closed_ordered_required.isl, constraints/annotations/closed_ordered_required_2.isl, constraints/annotations/closed_required.isl, constraints/annotations/validation_closed.isl
*Issue #, if available:*
https://github.com/amzn/ion-schema/pull/26
*Description of changes:*
These are test cases for https://github.com/amzn/ion-schema/pull/26 that did not get merged into `ion-schema-tests` when https://github.com/amzn/ion-schema-kotlin/pull/159 was merged.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Add tests for 'closed' annotations

constraints/annotations/ordered_mixed.isl
*Issue #, if available:*
None.
*Description of changes:*
Removes the `optional::` annotation from the list of annotations. The `optional::` annotation is only allowed on list elements for the `annotations` constraint, not on the list itself.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Fix invalid ISL in a test case

constraints/ordered_elements/occurs_4.isl
https://github.com/amzn/ion-schema/issues/62
Adds test case for `ordered_elements` to cover the incorrect, unexpected behavior mentioned in https://github.com/amzn/ion-schema/issues/62.
=> Adds additional test case for ordered_elements

constraints/timestamp_precision/min_and_max.isl
https://github.com/amzn/ion-schema-kotlin/issues/193
Adds a test case to cover the cases in https://github.com/amzn/ion-schema-kotlin/issues/193.
=> Add test cases for timestamp precision ranges using 'min' and 'max'

constraints/codepoint_length/exact.isl
https://github.com/amzn/ion-schema-kotlin/issues/190
Adds test cases to cover the bug mentioned in https://github.com/amzn/ion-schema-kotlin/issues/190.
=> Add test cases for codepoint_length that include codepoints made of multiple code units

constraints/valid_values/timestamps_with_known_and_unknown_offsets.isl
N/A
I've discovered a bug in `ion-schema-kotlin`, and this test case reproduces it. Essentially, there's an incorrect short-circuit evaluation of timestamps with unknown offsets in the `valid_values` constraint. If a timestamp with an unknown offset is compared to a range, `valid_values` will add an issue _even if there are other values that it could match_.
This test case should pass (according to the spec), but it is currently failing in `ion-schema-kotlin`.
=> Adds test for valid_values with unknown local offset mixed with other timestamp ranges

constraints/annotations/closed_no_annotations.isl, constraints/annotations/unordered_optional.isl
Test cases for https://github.com/amzn/ion-schema/pull/73
This change adds two test cases to make sure that a `document` does not match an `annotations` constraint that allows an empty list of annotations.
There are no new meaningful test cases we could for the `valid_values` constraint as applied to `document`s because there is no representation for a `document` literal in ISL. It is already impossible to construct a `valid_values` constraint that could match a `document`.
=> Adds test cases for annotations constraint applied to documents

.github/workflows/main.yml, ion_schema_1_0/constraints/occurs/ordered_elements.isl, ion_schema_1_0/schema/deferred_type_resolution.isl, ion_schema_tests.isl, validate-test-cases
N/A
Adds a GHA workflow to validate test case files. This includes:
* A schema that defines a valid test case file
* A script that runs `ion beta schema validate` on all test files
* A workflow that installs `ion-cli` and runs the validation script
* Removes empty line comments from two ISL files because `ion-rust` cannot parse them
The output is a little rough to use, but this is at least a start.
Examples of this workflow running:
* Fail: https://github.com/popematt/ion-schema-tests/actions/runs/3103001669/jobs/5025854836
* Pass: https://github.com/popematt/ion-schema-tests/actions/runs/3103003819/jobs/5025859515
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> Adds a GHA workflow to validate test case files

ion_schema_2_0/constraints/all_of.isl, ion_schema_2_0/constraints/any_of.isl, ion_schema_2_0/constraints/byte_length.isl, ion_schema_2_0/constraints/codepoint_length.isl, ion_schema_2_0/constraints/container_length.isl, ion_schema_2_0/constraints/not.isl, ion_schema_2_0/constraints/one_of.isl, ion_schema_2_0/constraints/type.isl, ion_schema_2_0/constraints/utf8_byte_length.isl, ion_schema_2_0/util.isl
#32 
Adds test cases for the `*_length`, `any_of`, `all_of`, `one_of`, `type`, and `not` constraints.
=> Adds test cases for Ion Schema 2.0 `*_length` and logic constraints

ion_schema_2_0/constraints/annotations-simplified.isl, ion_schema_2_0/constraints/annotations-standard.isl, ion_schema_2_0/constraints/field_names.isl, ion_schema_2_0/constraints/fields.isl, ion_schema_2_0/constraints/ordered_elements.isl
#32 
Adds test cases for `annotations`, `field_names`, `fields`, `ordered_elements` constraints.
=> Adds test cases for annotations, field_names, fields, ordered_elements for Ion Schema 2.0

ion_schema_2_0/constraints/regex-invalid.isl, ion_schema_2_0/constraints/regex.isl
#32 
Adds Ion Schema 2.0 test cases for regex constraint.
I can split this into a few more files if you think that would help with readability and maintainability.
=> Adds Ion Schema 2.0 test cases for regex constraint

README.md, ion_schema_1_0/schema/import/invalid_duplicate_import.isl, ion_schema_1_0/schema/import/invalid_duplicate_import_type.isl, ion_schema_1_0/schema/import/invalid_duplicate_type.isl, ion_schema_1_0/schema/import/invalid_transitive_import_of_schema.isl, ion_schema_1_0/schema/import/invalid_transitive_import_of_type.isl, ion_schema_1_0/schema/import/invalid_transitive_import_of_type_by_alias.isl, ion_schema_1_0/schema/invalid_missing_schema_footer.isl, ion_schema_1_0/schema/invalid_missing_schema_header.isl, ion_schema_1_0/schema/invalid_reuse_of_type_name.isl, ion_schema_1_0/schema/invalid_unknown_type.isl, ion_schema_2_0/constraints/all_of.isl, ion_schema_2_0/constraints/annotations-standard.isl, ion_schema_2_0/constraints/any_of.isl, ion_schema_2_0/constraints/byte_length.isl, ion_schema_2_0/constraints/codepoint_length.isl, ion_schema_2_0/constraints/container_length.isl, ion_schema_2_0/constraints/exponent.isl, ion_schema_2_0/constraints/one_of.isl, ion_schema_2_0/constraints/precision.isl, ion_schema_2_0/constraints/regex-invalid.isl, ion_schema_2_0/constraints/timestamp_precision.isl, ion_schema_2_0/constraints/utf8_byte_length.isl, ion_schema_2_0/constraints/valid_values-ranges.isl, ion_schema_tests.isl
#32 
Updates the test spec with a way to mark tests that should be skipped when testing with ISL for ISL, and updates all Ion Schema Tests that need to be skipped.
Rather than having a blocked/skip list in every implementation that runs the ISL for ISL tests, we should just mark the test cases themselves and include a reason why the test case is to be skipped. This approach is better than the existing approach because it is more fine-grained than having a file-based blocked/skip list, and it documents the reason the particular test cases are skipped.
=> Adds flag to mark some tests as out-of-scope for ion-schema-schemas

README.md, ion_schema_1_0/schema/import/import_type_unknown.isl, ion_schema_1_0/schema/import/invalid_duplicate_import.isl, ion_schema_1_0/schema/import/invalid_duplicate_import_type.isl, ion_schema_1_0/schema/import/invalid_duplicate_type.isl, ion_schema_1_0/schema/import/invalid_transitive_import_of_schema.isl, ion_schema_1_0/schema/import/invalid_transitive_import_of_type.isl, ion_schema_1_0/schema/import/invalid_transitive_import_of_type_by_alias.isl, ion_schema_1_0/schema/invalid_missing_schema_footer.isl, ion_schema_1_0/schema/invalid_missing_schema_header.isl, ion_schema_1_0/schema/invalid_reuse_of_type_name.isl, ion_schema_1_0/schema/invalid_unknown_type.isl, ion_schema_1_0/schema/invalid_unnamed_type.isl, ion_schema_2_0/schema/ion_schema_version_markers.isl, ion_schema_2_0/schema/schema_footer.isl, ion_schema_2_0/schema/schema_header.isl, ion_schema_2_0/schema/type.isl, ion_schema_tests.isl
#32 
* Changes `invalid_schema` to `invalid_schemas`
* Updates all Ion Schema 1.0 tests to reflect that change
* Adds Ion Schema 2.0 test cases for invalid headers, footers, and Ion Schema version markers
=> Adds negative tests for ISL 2.0 top-level schema elements

.editorconfig, ion_schema_1_0/constraints/byte_length/invalid.isl, ion_schema_1_0/constraints/codepoint_length/invalid.isl, ion_schema_1_0/constraints/container_length/invalid.isl, ion_schema_1_0/constraints/occurs/invalid.isl, ion_schema_1_0/constraints/precision/invalid.isl, ion_schema_1_0/constraints/regex/invalid.isl, ion_schema_1_0/constraints/scale/invalid.isl, ion_schema_1_0/constraints/timestamp_precision/invalid.isl, ion_schema_1_0/constraints/utf8_byte_length/invalid.isl, ion_schema_1_0/constraints/valid_values/invalid.isl, ion_schema_1_0/constraints/valid_values/range_timestamp_invalid.isl, ion_schema_1_0/core_types/document.isl, ion_schema_1_0/schema/import/import_type_unknown.isl
N/A
When working on #35, I missed some test cases that needed to be flagged as out of scope for ISL for ISL.
This PR causes ISL for ISL to skip invalid type tests for
* regexes (because there's no possible regular expression to validate regexes)
* all tests regarding ranges that are unsatisfiable
* tests for `document` not being allowed to be `nullable` (because ISL for Ion Schema 1.0 doesn't distinguish type names at all)
Also, skips an unknown import test case that was missed in the previous PR.
I meant to add the `.editorconfig` file in a separate PR since it is orthogonal to the test fixes, but I accidentally put it in here, so I'll leave it unless there's any objection.
_By submitting this pull request, I confirm that you can …
=> Adds flag to skip some Ion Schema 1.0 tests when running ISL for ISL.

README.md, ion_schema_2_0/open_content/top_level_user_content.isl, ion_schema_2_0/open_content/user_fields_declaration.isl, ion_schema_2_0/open_content/user_fields_in_schema_footer.isl, ion_schema_2_0/open_content/user_fields_in_schema_header.isl, ion_schema_2_0/open_content/user_fields_in_type_definition.isl, ion_schema_2_0/schema/schema_footer.isl, ion_schema_2_0/schema/type.isl, ion_schema_tests.isl
#32 
* [Adds valid_schemas test case type](https://github.com/amzn/ion-schema-tests/commit/38bd815af056e891f0383df31b67cae0cad94100)
* I realized that it would be helpful to have a way to assert that many schemas are valid without having to manage a separate file for each test case. I don't want "too many files" to discourage anyone from creating good test coverage.
* We don't need a `valid_types` test case because you can have more than one type in a schema document.
* [Adds test cases for Ion Schema 2.0 user content](https://github.com/amzn/ion-schema-tests/commit/05f7a34e7bba567ddc4ec99337cc41daa48eab5b)
* Includes test cases for user content in the schema header, schema footer, and type definitions as well as top-level user …
=> Adds tests for Ion Schema 2.0 user content

ion_schema_2_0/schema/schema_with_circularly_referencing_types.isl, ion_schema_2_0/schema/schema_with_recursive_type.isl, ion_schema_2_0/schema/schema_with_type_referenced_before_it_is_defined.isl, ion_schema_2_0/schema/type.isl
#32 
Adds test cases for:
* no duplicate type names in a schema
* deferred resolution of type references
* recursive type definition
* circularly referencing type definitions
=> Adds more tests cases for Ion Schema 2.0 types

README.md, ion_schema_2_0/constraints/annotations-simplified.isl, ion_schema_2_0/constraints/annotations-standard.isl, ion_schema_2_0/constraints/byte_length.isl, ion_schema_2_0/constraints/codepoint_length.isl, ion_schema_2_0/constraints/container_length.isl, ion_schema_2_0/constraints/contains.isl, ion_schema_2_0/constraints/element.isl, ion_schema_2_0/constraints/exponent.isl, ion_schema_2_0/constraints/not.isl, ion_schema_2_0/constraints/precision.isl, ion_schema_2_0/constraints/timestamp_offset.isl, ion_schema_2_0/constraints/timestamp_precision.isl, ion_schema_2_0/constraints/type.isl, ion_schema_2_0/constraints/utf8_byte_length.isl, ion_schema_2_0/constraints/valid_values-ranges.isl
*Issue #, if available:*
fixes #36
fixes #34
*Description of changes:*
* Gets rid of all the test type names that were the type definition.
* Replaces all of the "must not be non-empty" (which really should have been "must be non-empty") to be "must be satisfiable" to better convey the intent.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Improves test names

ion_schema_2_0/constraints/contains.isl, ion_schema_2_0/open_content/top_level_user_content.isl
None
* Fixes a test name and type name that doesn't match
* Adds `null.struct` and `null.symbol` to open content tests to make sure that ISL top-level struct (type, header, footer) logic and ISL version marker logic handle nulls correctly.
----
=> Fix a test name and add two open content edge cases

ion_schema_2_0/imports/diamond/header_import_a.isl, ion_schema_2_0/imports/diamond/inline_import_a.isl, ion_schema_2_0/imports/header_imports.isl, ion_schema_2_0/imports/invalid_imports.isl, ion_schema_2_0/imports/tree/header_import_a.isl, ion_schema_2_0/imports/tree/inline_import_a.isl, ion_schema_2_0/open_content/user_fields_declaration.isl
None
* Some test cases for user_reserved_fields were passing, but for the wrong reason. They were testing to make sure that certain prohibited fields would cause the schema to be invalid, but the test data was already invalid _in a different way_. This commit fixes those test cases.
* Some test cases that require resolving imports cannot be detected as invalid by Ion Schema Schemas, so I have added the flag to indicate that.
----
=> Fix user_reserved_fields test cases and mark import test cases that cannot be detected by ion-schema-schemas

ion_schema_1_0/schema/import/cycles/header_import_a.isl, ion_schema_1_0/schema/import/cycles/header_import_b.isl, ion_schema_1_0/schema/import/cycles/header_import_by_type_a.isl, ion_schema_1_0/schema/import/cycles/header_import_by_type_b.isl, ion_schema_1_0/schema/import/cycles/header_import_by_type_with_alias_a.isl, ion_schema_1_0/schema/import/cycles/header_import_by_type_with_alias_b.isl, ion_schema_1_0/schema/import/cycles/inline_import_a.isl, ion_schema_1_0/schema/import/cycles/inline_import_b.isl
None
Adds tests for import cycles to the Ion Schema 1.0 test suite. They are basically a copy/paste of the equivalent tests for Ion Schema 2.0, with the ISL 2.0 version marker removed and the import paths updated accordingly.
----
=> Adds tests for cyclical imports for Ion Schema 1.0

ion_schema_1_0/nullable.isl, ion_schema_2_0/null_or.isl
None
Adds tests for `nullable::` and `$null_or::`.
----
=> Adds tests cases for nullability annotations

ion_schema_2_0/schema/ion_schema_version_markers.isl, ion_schema_2_0/schema/schema_footer.isl, ion_schema_2_0/schema/schema_header.isl
Follow up for amazon-ion/ion-schema#118
* Updates tests so that footer is optional, and so that anything can come after a footer.
* Adds some clarifying notes for the ordering of the version marker in the schema
* Fixes some test with typos.
----
=> Updates version marker, header, and footer tests for amazon-ion/ion-schema#118
